org: gelca
app: trial-1
service: aws-node-animoeats
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_URL: "postgresql://postgres:23postgres@localhost:5432/animoeats"

functions:
  # loginUser:
  #   handler: functions/user.loginUser
  #   events:
  #     - http:
  #         path: user/login
  #         method: post

  # registerUser:
  #   handler: functions/user.registerUser
  #   events:
  #     - http:
  #         path: user/register
  #         method: post

  # updateUserTDEE:
  #   handler: functions/user.updateUserProfile
  #   events:
  #     - http:
  #         path: user/tdee
  #         method: put

  # updateUserHealthProfile:
  #   handler: functions/user.updateUserHealthProfile
  #   events:
  #     - http:
  #         path: user/update/profile
  #         method: patch

  # updateAllergies:
  #   handler: functions/user.updateAllergies
  #   events:
  #     - http:
  #         path: user/update/allergies
  #         method: put

  # completeRegistration:
  #   handler: functions/user.completeRegistration
  #   events:
  #     - http:
  #         path: user/register/complete
  #         method: post

  # createCategory:
  #   handler: functions/foodCategory.createFoodCategory
  #   events:
  #     - http:
  #         path: foodCategory/create
  #         method: post

  # getAvailableFoodItems:
  #   handler: functions/food.handleGetAvailableFoodItems
  #   events:
  #     - http:
  #         path: /food/{userId}/available
  #         method: get

  # createFoodSwipeHistory:
  #   handler: functions/food.handleCreateFoodSwipeHistory
  #   events:
  #     - http:
  #         path: /food/swipes
  #         method: post
  #         request:
  #           parameters:
  #             paths:
  #               userId: true

  getUserHealthProfile:
    handler: functions/user.getUserHealthProfile
    events:
      - http:
          path: /user/{userId}/health-profile
          method: get

  getUserAllergies:
    handler: functions/user.getUserAllergies
    events:
      - http:
          path: /user/{userId}/allergies
          method: get

  getUserDetails:
    handler: functions/user.getUserDetails
    events:
      - http:
          path: /user/{userId}/details
          method: get

plugins:
  - serverless-offline
